### ISSUE TITLE
Automation results submission for the pizza task

### ISSUE THREAD

**Issue by LyashenkoGS** [LyashenkoGS/GoogleHashCode2017#2]
Google checks sent result files online. So to avoid unit test writing we will write a test on Selenium WebDriver that sends results to the [submission page](https://hashcodejudge.withgoogle.com/#/rounds/6553823069863936/submissions/)
and parse scores

**Comment by LyashenkoGS** [comment]
I finished up with SeleniumIDE and firefox. Here is my test case. Need to substitute file paths to appropriate.
```
type	//input[@type="file"][1]	/Users/greg/Desktop/Hamcrest-1.3.pdf
pause	1000	
type	//input[@type="file"][1]	/Users/greg/Desktop/Hamcrest-1.3.pdf
pause	1000	
type	//input[@type="file"][1]	/Users/greg/Desktop/Hamcrest-1.3.pdf
pause	1000	
type	//input[@type="file"][1]	/Users/greg/Desktop/Hamcrest-1.3.pdf
pause	1000	
type	//input[@type="file"][1]	/Users/greg/Desktop/Hamcrest-1.3.pdf
pause	1000	
click	xpath=(//button[@type='button'])[25]	

```

**Comment by LyashenkoGS** [comment]
Final solution  
scripts:
1. For zipping the source code(bash)
2. To submit the source code archive and output files via a web form(selenium)

I think a better option is to migrate a selenium script to Java but this way we will encounter a problem with authentification or connecting to an open browser. 

See the branch `automationResultsSubmission`

https://www.youtube.com/watch?v=Wg7s3CtIeCs&feature=youtu.be

**Comment by seajer** [comment]
I'm finishing with with selenium code (but u shoud be logged in from u'r google account in this Chrome browser) when it works i'll comit it.
